// ============================================================================
// PLACEHOLDER / SYNTHETIC SAMPLE DATA -- NOT REAL EMPLOYEES
// ============================================================================
// This file is hand-written fake data so the app is demoable before a real
// census export is available. It covers multiple departments, ~3 years of
// hire dates, a mix of onsite/remote work locations, and a handful of
// synthetic terminations with reasons and voluntary/regrettable flags.
//
// REGENERATE THIS FILE from a real export before sharing this dashboard:
//   node scripts/build-data.mjs "<path to census export.xlsx>" ["<path to V&R workbook.xlsx>"]
// See README.md for the exact expected file format and columns.
//
// PRIVACY: every record below contains ONLY: department, work location,
// worker category, position status, contractor flag, job title, annual
// salary, hire/rehire/termination dates, termination reason, and the
// voluntary/regrettable flags. There is no name, employee id, or manager
// field anywhere in this file, and scripts/build-data.mjs strips those
// fields from any real export before writing here -- see its comments.
// ============================================================================
export const RECORDS = [
  {
    "department": "People Operations",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Recruiter",
    "annual_salary": 75500,
    "hire_date": "2025-08-03",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Care Coordination",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Care Coordinator",
    "annual_salary": 73500,
    "hire_date": "2024-01-25",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "OH",
    "work_location": "R-OH - Remote-Ohio",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Senior Software Engineer",
    "annual_salary": 110500,
    "hire_date": "2026-05-02",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "OH",
    "work_location": "R-OH - Remote-Ohio",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Engineering Manager",
    "annual_salary": 102000,
    "hire_date": "2025-11-04",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "QA Analyst",
    "annual_salary": 106000,
    "hire_date": "2023-12-31",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "People Operations",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "HR Generalist",
    "annual_salary": 84000,
    "hire_date": "2025-01-22",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Finance",
    "location_state": "TX",
    "work_location": "R-TX - Remote-Texas",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Staff Accountant",
    "annual_salary": 91000,
    "hire_date": "2024-08-01",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Software Engineer",
    "annual_salary": 105500,
    "hire_date": "2023-02-04",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "QA Analyst",
    "annual_salary": 115000,
    "hire_date": "2025-03-03",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Member Services",
    "location_state": "FL",
    "work_location": "R-FL - Remote-Florida",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Member Services Rep",
    "annual_salary": 63000,
    "hire_date": "2026-05-03",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Care Coordination",
    "location_state": "NY",
    "work_location": "OSNY - Onsite-New York",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "RN Care Manager",
    "annual_salary": 70000,
    "hire_date": "2023-02-05",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Marketing",
    "location_state": "CA",
    "work_location": "R-CA - Remote-California",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Marketing Specialist",
    "annual_salary": 58500,
    "hire_date": "2024-04-24",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Finance",
    "location_state": "GA",
    "work_location": "R-GA - Remote-Georgia",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "FP&A Analyst",
    "annual_salary": 89000,
    "hire_date": "2023-08-19",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "NY",
    "work_location": "OSNY - Onsite-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Nurse Practitioner",
    "annual_salary": 90000,
    "hire_date": "2023-11-14",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Engineering Manager",
    "annual_salary": 114000,
    "hire_date": "2025-03-17",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "People Operations",
    "location_state": "GA",
    "work_location": "R-GA - Remote-Georgia",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "HR Generalist",
    "annual_salary": 82500,
    "hire_date": "2026-01-31",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Clinical Ops Director",
    "annual_salary": 99500,
    "hire_date": "2023-06-22",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "BC",
    "work_location": "OSVAN - Onsite-Vancouver",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "QA Analyst",
    "annual_salary": 110500,
    "hire_date": "2023-04-01",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Marketing",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Marketing Specialist",
    "annual_salary": 71500,
    "hire_date": "2026-06-20",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Revenue Cycle",
    "location_state": "NY",
    "work_location": "OSNY - Onsite-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Claims Analyst",
    "annual_salary": 75000,
    "hire_date": "2023-10-24",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "PA",
    "work_location": "R-PA - Remote-Pennsylvania",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Clinical Ops Analyst",
    "annual_salary": 82500,
    "hire_date": "2024-01-26",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Member Services",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Senior Member Services Rep",
    "annual_salary": 66500,
    "hire_date": "2025-05-18",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Care Coordination",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Care Coordinator",
    "annual_salary": 76000,
    "hire_date": "2023-09-01",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Software Engineer",
    "annual_salary": 99000,
    "hire_date": "2024-04-07",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Finance",
    "location_state": "CA",
    "work_location": "R-CA - Remote-California",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Staff Accountant",
    "annual_salary": 79000,
    "hire_date": "2023-09-19",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "People Operations",
    "location_state": "CA",
    "work_location": "R-CA - Remote-California",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Recruiter",
    "annual_salary": 70000,
    "hire_date": "2025-09-03",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "People Operations",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "People Ops Manager",
    "annual_salary": 85000,
    "hire_date": "2024-06-14",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "People Operations",
    "location_state": "PA",
    "work_location": "R-PA - Remote-Pennsylvania",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Recruiter",
    "annual_salary": 63500,
    "hire_date": "2026-01-20",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Revenue Cycle",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Claims Analyst",
    "annual_salary": 71000,
    "hire_date": "2024-10-01",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "CA",
    "work_location": "R-CA - Remote-California",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Nurse Practitioner",
    "annual_salary": 80000,
    "hire_date": "2026-01-16",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Care Coordination",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Care Coordinator",
    "annual_salary": 74000,
    "hire_date": "2025-08-12",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Care Coordination",
    "location_state": "OH",
    "work_location": "R-OH - Remote-Ohio",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Care Coordinator",
    "annual_salary": 65000,
    "hire_date": "2023-07-16",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Revenue Cycle",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Revenue Cycle Manager",
    "annual_salary": 59500,
    "hire_date": "2025-04-27",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Member Services",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Member Services Rep",
    "annual_salary": 61500,
    "hire_date": "2024-04-23",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "BC",
    "work_location": "OSVAN - Onsite-Vancouver",
    "worker_category": "Contractor",
    "position_status": "active",
    "is_contractor": true,
    "role": "Nurse Practitioner",
    "annual_salary": 80000,
    "hire_date": "2024-01-13",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "BC",
    "work_location": "OSVAN - Onsite-Vancouver",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Clinical Ops Director",
    "annual_salary": 78500,
    "hire_date": "2026-04-05",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Marketing",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Content Manager",
    "annual_salary": 83000,
    "hire_date": "2024-02-17",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Member Services",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Member Services Rep",
    "annual_salary": 58000,
    "hire_date": "2024-02-12",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Care Coordination",
    "location_state": "NY",
    "work_location": "OSNY - Onsite-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Care Coordinator",
    "annual_salary": 68000,
    "hire_date": "2024-07-28",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Member Services",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Senior Member Services Rep",
    "annual_salary": 64500,
    "hire_date": "2026-01-18",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "Nurse Practitioner",
    "annual_salary": 101500,
    "hire_date": "2023-05-14",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Core Technology",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "active",
    "is_contractor": false,
    "role": "QA Analyst",
    "annual_salary": 100500,
    "hire_date": "2026-07-02",
    "rehire_date": null,
    "termination_date": null,
    "termination_reason": null,
    "voluntary_flag": null,
    "regrettable_flag": null
  },
  {
    "department": "Clinical Operations",
    "location_state": "FL",
    "work_location": "R-FL - Remote-Florida",
    "worker_category": "Contractor",
    "position_status": "terminated",
    "is_contractor": true,
    "role": "Clinical Ops Director",
    "annual_salary": 93000,
    "hire_date": "2023-04-23",
    "rehire_date": null,
    "termination_date": "2024-11-21",
    "termination_reason": "S - Voluntary Resignation",
    "voluntary_flag": true,
    "regrettable_flag": false
  },
  {
    "department": "People Operations",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "People Ops Manager",
    "annual_salary": 81500,
    "hire_date": "2023-05-27",
    "rehire_date": null,
    "termination_date": "2023-11-30",
    "termination_reason": "Layoff",
    "voluntary_flag": false,
    "regrettable_flag": false
  },
  {
    "department": "Clinical Operations",
    "location_state": "TX",
    "work_location": "R-TX - Remote-Texas",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "Clinical Ops Director",
    "annual_salary": 98000,
    "hire_date": "2023-04-11",
    "rehire_date": null,
    "termination_date": "2025-07-31",
    "termination_reason": "N - Personal",
    "voluntary_flag": true,
    "regrettable_flag": false
  },
  {
    "department": "Revenue Cycle",
    "location_state": "NY",
    "work_location": "OSNY - Onsite-New York",
    "worker_category": "Contractor",
    "position_status": "terminated",
    "is_contractor": true,
    "role": "Billing Specialist",
    "annual_salary": 57000,
    "hire_date": "2023-08-07",
    "rehire_date": null,
    "termination_date": "2024-12-15",
    "termination_reason": "Involuntary - Attendance",
    "voluntary_flag": false,
    "regrettable_flag": false
  },
  {
    "department": "Core Technology",
    "location_state": "FL",
    "work_location": "R-FL - Remote-Florida",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "Software Engineer",
    "annual_salary": 107000,
    "hire_date": "2023-07-08",
    "rehire_date": null,
    "termination_date": "2025-05-01",
    "termination_reason": "Retired",
    "voluntary_flag": null,
    "regrettable_flag": false
  },
  {
    "department": "Core Technology",
    "location_state": "NY",
    "work_location": "OSNY - Onsite-New York",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "Software Engineer",
    "annual_salary": 121500,
    "hire_date": "2023-05-14",
    "rehire_date": null,
    "termination_date": "2024-01-11",
    "termination_reason": "Involuntary - Attendance",
    "voluntary_flag": false,
    "regrettable_flag": false
  },
  {
    "department": "Core Technology",
    "location_state": "NY",
    "work_location": "R-NY - Remote-New York",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "QA Analyst",
    "annual_salary": 99500,
    "hire_date": "2023-06-27",
    "rehire_date": null,
    "termination_date": "2025-03-01",
    "termination_reason": "S - Voluntary Resignation",
    "voluntary_flag": true,
    "regrettable_flag": false
  },
  {
    "department": "Finance",
    "location_state": "BC",
    "work_location": "OSVAN - Onsite-Vancouver",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "Staff Accountant",
    "annual_salary": 84500,
    "hire_date": "2024-08-21",
    "rehire_date": null,
    "termination_date": "2026-09-10",
    "termination_reason": "Involuntary - Attendance",
    "voluntary_flag": false,
    "regrettable_flag": false
  },
  {
    "department": "Core Technology",
    "location_state": "TX",
    "work_location": "OSDAL - Onsite-Dallas",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "Senior Software Engineer",
    "annual_salary": 118500,
    "hire_date": "2024-11-09",
    "rehire_date": null,
    "termination_date": "2026-09-13",
    "termination_reason": "Layoff",
    "voluntary_flag": false,
    "regrettable_flag": false
  },
  {
    "department": "Core Technology",
    "location_state": "GA",
    "work_location": "R-GA - Remote-Georgia",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "QA Analyst",
    "annual_salary": 122000,
    "hire_date": "2024-09-20",
    "rehire_date": null,
    "termination_date": "2026-04-21",
    "termination_reason": "Involuntary - Attendance",
    "voluntary_flag": false,
    "regrettable_flag": true
  },
  {
    "department": "Member Services",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Full-Time",
    "position_status": "terminated",
    "is_contractor": false,
    "role": "Member Services Rep",
    "annual_salary": 64500,
    "hire_date": "2023-10-10",
    "rehire_date": null,
    "termination_date": "2024-01-06",
    "termination_reason": "Retired",
    "voluntary_flag": null,
    "regrettable_flag": false
  },
  {
    "department": "Finance",
    "location_state": "IL",
    "work_location": "OSCHI - Onsite-Chicago",
    "worker_category": "Contractor",
    "position_status": "terminated",
    "is_contractor": true,
    "role": "Controller",
    "annual_salary": 81000,
    "hire_date": "2023-08-31",
    "rehire_date": null,
    "termination_date": "2026-01-05",
    "termination_reason": "Retired",
    "voluntary_flag": null,
    "regrettable_flag": false
  },
  {
    "department": "Revenue Cycle",
    "location_state": "OH",
    "work_location": "R-OH - Remote-Ohio",
    "worker_category": "Contractor",
    "position_status": "terminated",
    "is_contractor": true,
    "role": "Claims Analyst",
    "annual_salary": 71500,
    "hire_date": "2024-04-15",
    "rehire_date": null,
    "termination_date": "2026-01-27",
    "termination_reason": "M - Performance",
    "voluntary_flag": false,
    "regrettable_flag": true
  }
];
